[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
num = "0.4.3"
rayon = "1.10.0"