[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# vulkano = "0.34.0"
# vulkano-shaders = "0.34.0"
rand = "0.8.5"
# shaderc-sys = "0.8.3"